version: '3.8'

services:
  db:
    image: postgres
    container_name: data_base_pg
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_base
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # migrations:
  #   image: mcr.microsoft.com/dotnet/sdk:8.0
  #   working_dir: /App
  #   volumes:
  #     - ./DeathTime.ASP.NET:/App
  #   environment:
  #     - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=data_base;User Id=user;Password=password;
  #   depends_on:
  #     - db
  #   entrypoint: ["sh", "-c", "dotnet tool install --global dotnet-ef && export PATH=\"$PATH:/root/.dotnet/tools\" && dotnet-ef database update"]

  # web:
  #   build: ./DeathTime.ASP.NET
  #   container_name: dotnet_app
  #   restart: always
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=data_base;User Id=user;Password=password;
  #   ports:
  #     - "5024:5024"
  #   depends_on:
  #     - db
  #     - migrations
  #   command: ["dotnet", "DeathTime.ASP.NET.dll"]


