version: '3.8'

services:
  db:
    image: postgres
    container_name: data_base_pg
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_base
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - compose-bridge

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5024
      - ASPNETCORE_HTTPS_PORTS=5024
    container_name: death_time.net
    image: ${DOCKER_REGISTRY-}d_t_source
    build:
      context: .
      dockerfile: D_T_Source/Dockerfile
    ports:
      - "5024:5024"
    networks:
      - compose-bridge
    depends_on:
      - db

networks:
  compose-bridge:
    driver: bridge
